server:
  port: 8080
spring:
  application:
    name: DoAnJava
  datasource:
    url: jdbc:mysql://localhost:3307/marketplace_db
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
