server:
  port: 8080
spring:
  application:
    name: DoAnJava
  datasource:
    url: jdbc:mysql://database-1.cgxq828ugpr9.us-east-1.rds.amazonaws.com:3306/marketplace_db
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
