server:
  port: 8080
spring:
  application:
    name: DoAnJava
  datasource:
#    url: jdbc:mysql://database-1.cgxq828ugpr9.us-east-1.rds.amazonaws.com:3306/marketplace_db
#    username: root
#    password: admin123
    url: jdbc:mysql://localhost:3307/marketplace_db2
    username: root
    password: ductu2004
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000  
