server:
  port: 8080
spring:
  application:
    name: DoAnJava
  datasource:
    url: jdbc:mysql://localhost:3306/marketplace_db2
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000  

app:
  admin:
    email: admin@example.com
  base-domain: http://localhost:3000

stripe:
  api-key: sk_test_51S9SX3L9RJOfTfprx3DuvELYlakO3fbRRL6B2BYyZJVnUB074iBTAaUPAujoDnNfl4C7OQRoWDhB8OJMWIPik3I0004xlmoyuB